### PR TITLE
Addresses issues that arose from the initial git action update

### PR DESCRIPTION
**Pull request by cloke**

### CODE REVIEW

**Comment by cloke** [comment]
The failures in the tests are to be expected on ember 4.x. Subsequent PRs will work to upgrade the actual add-on.

**Review by knownasilya — APPROVED** [review]

**Comment by knownasilya** [comment]
@adopted-ember-addons/admin any ideas how to remove the travis-ci step? I don't see anything in settings for the repo.

**Comment by Turbo87** [comment]
Bildschirmfoto 2022-05-03 um 17 12 54

I've removed the travis-ci check there. You might have to amend and push again to trigger another CI run.

**Comment by knownasilya** [comment]
@adopted-ember-addons/admin it also looks like this lib is not in the npm adopted org. I'm not on it so I can't change it.

**Pull request merged**
